package enums;

public enum Nature {
    COMPONENTS,
    SERVER_COMPONENT,
    COMPUTER,
    NETWORKING,
    DISPLAY_DEVICE,
    OTHER_EQUIPMENT,
    UPS,
    SUPPLIES,
    MOBILE_DEVICE,
    PRINTING_COPYING_DEVICE,
    MONITOR,
    SERVER,
    SUPPORT_NON_HARDWARE,
    SERVER_EXTERNAL_DEVICE,
    PERIPHERALS,
    OTHER
}
